comment:
  layout: "diff, files"
  behavior: default
  require_changes: true

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
