language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly" # currently points to 3.7-dev
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements-dev.txt
# command to run tests
script:
    - make tests
    - flake8 --exclude pycondor/__init__.py pycondor
    - travis-sphinx --nowarn --source=docs build

after_success:
    - travis-sphinx deploy
